spring:
  application:
    name: HostelServiceProject

  datasource:
    url: jdbc:postgresql://localhost:5000/java_db
    username: admin
    password: j@varasul2005

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update

server:
  port: 5342




